
name: Push Check Pipeline

on: [push, pull_request]

jobs:
  build:
    name: Build & Lint Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn

      - name: Enforce js code style
        run: yarn lint:js

      - name: Enforce styles code style
        run: yarn lint:style

      - name: Build without failing
        run: yarn build
